// Generated by tools/gen_game_tables.py from the game's own Excel sheets.
// Do not edit by hand: re-run the generator after a patch instead.
#pragma once

#include <cstdint>
#include <string>
#include <string_view>

namespace hub::game {

/// Name from the game's Action sheet.
/// Empty when the sheet carries no such row. Defined in src/common/src/game_tables.cpp,
/// so including this header does not pull the table into every translation unit.
[[nodiscard]] std::string_view action_sheet_name(uint32_t id) noexcept;

/// Display name, falling back to "Action <id>" for ids the sheet lacks.
[[nodiscard]] inline std::string action_name(uint32_t id) {
    const std::string_view name = action_sheet_name(id);
    return name.empty() ? "Action " + std::to_string(id) : std::string(name);
}

/// The GCD a player action starts and its cast time, both in 100 ms and unadjusted for
/// speed. All zero for an action off the global cooldown.
struct GcdTiming {
    uint16_t recast_100ms{0};
    uint16_t cast_100ms{0};
};

/// Defined in src/common/src/game_tables.cpp, like the two below.
[[nodiscard]] GcdTiming gcd_timing(uint32_t id) noexcept;

/// True for a player action on the global cooldown (cooldown group 58, as its
/// own group or its additional one).
[[nodiscard]] bool is_gcd_action(uint32_t id) noexcept;

/// True for an action someone presses: every button has a cooldown group. Auto-attacks,
/// pet actions and the effects the game fires by itself have none, and neither does a
/// Limit Break.
[[nodiscard]] bool is_pressed_action(uint32_t id) noexcept;

} // namespace hub::game
