// Generated by tools/gen_game_tables.py from the game's own Excel sheets.
// Do not edit by hand: re-run the generator after a patch instead.
#pragma once

#include <algorithm>
#include <array>
#include <cstdint>

namespace hub::game {

/// What a hit is guaranteed to be. Rate buffs raise a guaranteed hit's damage
/// instead of its chance.
enum class GuaranteedHit : uint8_t {
    None = 0,
    Crit = 1,
    DirectHit = 2,
    CritDirectHit = 3,
};

struct GuaranteedHitEntry {
    uint32_t id;
    GuaranteedHit hit;
};

/// Actions whose text says rate buffs raise their damage: every one is a guaranteed
/// hit, from the ActionTransient sheet.
constexpr std::array<GuaranteedHitEntry, 12> GUARANTEED_HIT_ACTIONS{{
    {  7487u, GuaranteedHit::Crit},          // Midare Setsugekka
    { 16463u, GuaranteedHit::CritDirectHit}, // Chaotic Cyclone
    { 16465u, GuaranteedHit::CritDirectHit}, // Inner Chaos
    { 16486u, GuaranteedHit::Crit},          // Kaeshi: Setsugekka
    { 25753u, GuaranteedHit::CritDirectHit}, // Primal Rend
    { 25781u, GuaranteedHit::Crit},          // Ogi Namikiri
    { 25782u, GuaranteedHit::Crit},          // Kaeshi: Namikiri
    { 25792u, GuaranteedHit::CritDirectHit}, // Starfall Dance
    { 36925u, GuaranteedHit::CritDirectHit}, // Primal Ruination
    { 36966u, GuaranteedHit::Crit},          // Tendo Setsugekka
    { 36968u, GuaranteedHit::Crit},          // Tendo Kaeshi Setsugekka
    { 36982u, GuaranteedHit::CritDirectHit}, // Full Metal Field
}};

/// Statuses that make the holder's next weaponskills guaranteed hits, from the same
/// sentence on the Status sheet.
constexpr std::array<GuaranteedHitEntry, 4> GUARANTEED_HIT_STATUSES{{
    {    86u, GuaranteedHit::CritDirectHit}, // Berserk
    {   116u, GuaranteedHit::Crit},          // Life Surge
    {   851u, GuaranteedHit::CritDirectHit}, // Reassembled
    {  1177u, GuaranteedHit::CritDirectHit}, // Inner Release
}};

/// Actions that only crit for certain with their form bonus.
constexpr std::array<uint32_t, 3> FORM_BONUS_CRIT_ACTIONS{{
        53u, // Bootshine
     25767u, // Shadow of the Destroyer
     36945u, // Leaping Opo
}};

/// Statuses that grant that form bonus.
constexpr std::array<uint32_t, 2> FORM_BONUS_STATUSES{{
       107u, // Opo-opo Form
      2513u, // Formless Fist
}};

namespace detail {
[[nodiscard]] constexpr GuaranteedHit find_guaranteed(const auto& table, uint32_t id) noexcept {
    const auto it = std::lower_bound(table.begin(), table.end(), id,
        [](const GuaranteedHitEntry& entry, uint32_t value) { return entry.id < value; });
    return (it != table.end() && it->id == id) ? it->hit : GuaranteedHit::None;
}
} // namespace detail

/// What `action_id` always lands as; None when it rolls like any other hit.
[[nodiscard]] constexpr GuaranteedHit guaranteed_hit_of_action(uint32_t action_id) noexcept {
    return detail::find_guaranteed(GUARANTEED_HIT_ACTIONS, action_id);
}

/// What a weaponskill used under `status_id` lands as; None for any other status.
[[nodiscard]] constexpr GuaranteedHit guaranteed_hit_of_status(uint32_t status_id) noexcept {
    return detail::find_guaranteed(GUARANTEED_HIT_STATUSES, status_id);
}

[[nodiscard]] constexpr bool is_form_bonus_crit_action(uint32_t action_id) noexcept {
    return std::binary_search(FORM_BONUS_CRIT_ACTIONS.begin(), FORM_BONUS_CRIT_ACTIONS.end(), action_id);
}

[[nodiscard]] constexpr bool is_form_bonus_status(uint32_t status_id) noexcept {
    return std::binary_search(FORM_BONUS_STATUSES.begin(), FORM_BONUS_STATUSES.end(), status_id);
}

} // namespace hub::game
