// Generated by tools/gen_game_tables.py from the game's own Excel sheets.
// Do not edit by hand: re-run the generator after a patch instead.
#pragma once

#include <cstdint>
#include <string>
#include <string_view>

namespace hub::game {

/// Name from the game's Status sheet.
/// Empty when the sheet carries no such row. Defined in src/common/game_tables.cpp,
/// so including this header does not pull the table into every translation unit.
[[nodiscard]] std::string_view status_sheet_name(uint32_t id) noexcept;

/// Display name, falling back to "Status <id>" for ids the sheet lacks.
[[nodiscard]] inline std::string status_name(uint32_t id) {
    const std::string_view name = status_sheet_name(id);
    return name.empty() ? "Status " + std::to_string(id) : std::string(name);
}

} // namespace hub::game
