// Generated by tools/gen_game_tables.py from the game's own Excel sheets.
// Do not edit by hand: re-run the generator after a patch instead.
#pragma once

#include <algorithm>
#include <array>
#include <cstdint>
#include <string_view>

namespace hub::game {

struct WorldEntry {
    uint16_t id;
    uint8_t data_center;
};

/// Every public world and its data center, a WorldDCGroupType row.
inline constexpr std::array<WorldEntry, 87> WORLD_TABLE{{
    {   21u,   9}, // Ravana
    {   22u,   9}, // Bismarck
    {   23u,   3}, // Asura
    {   24u,  10}, // Belias
    {   28u,   3}, // Pandaemonium
    {   29u,  10}, // Shinryu
    {   30u,  10}, // Unicorn
    {   31u,  10}, // Yojimbo
    {   32u,  10}, // Zeromus
    {   33u,   7}, // Twintania
    {   34u,   8}, // Brynhildr
    {   35u,   5}, // Famfrit
    {   36u,   7}, // Lich
    {   37u,   8}, // Mateus
    {   39u,   6}, // Omega
    {   40u,   4}, // Jenova
    {   41u,   8}, // Zalera
    {   42u,   7}, // Zodiark
    {   43u,   2}, // Alexander
    {   44u,   3}, // Anima
    {   45u,   1}, // Carbuncle
    {   46u,   2}, // Fenrir
    {   47u,   3}, // Hades
    {   48u,   3}, // Ixion
    {   49u,   1}, // Kujata
    {   50u,   1}, // Typhon
    {   51u,   2}, // Ultima
    {   52u,  10}, // Valefor
    {   53u,   5}, // Exodus
    {   54u,   4}, // Faerie
    {   55u,   5}, // Lamia
    {   56u,   7}, // Phoenix
    {   57u,   4}, // Siren
    {   58u,   1}, // Garuda
    {   59u,   2}, // Ifrit
    {   60u,  10}, // Ramuh
    {   61u,   3}, // Titan
    {   62u,   8}, // Diabolos
    {   63u,   4}, // Gilgamesh
    {   64u,   5}, // Leviathan
    {   65u,   4}, // Midgardsormr
    {   66u,   7}, // Odin
    {   67u,   7}, // Shiva
    {   68u,   1}, // Atomos
    {   69u,   2}, // Bahamut
    {   70u,   3}, // Chocobo
    {   71u,   6}, // Moogle
    {   72u,   1}, // Tonberry
    {   73u,   4}, // Adamantoise
    {   74u,   8}, // Coeurl
    {   75u,   8}, // Malboro
    {   76u,   2}, // Tiamat
    {   77u,   5}, // Ultros
    {   78u,   5}, // Behemoth
    {   79u,   4}, // Cactuar
    {   80u,   6}, // Cerberus
    {   81u,   8}, // Goblin
    {   82u,  10}, // Mandragora
    {   83u,   6}, // Louisoix
    {   85u,   6}, // Spriggan
    {   86u,   9}, // Sephirot
    {   87u,   9}, // Sophia
    {   88u,   9}, // Zurvan
    {   90u,   1}, // Aegis
    {   91u,   8}, // Balmung
    {   92u,   2}, // Durandal
    {   93u,   5}, // Excalibur
    {   94u,   1}, // Gungnir
    {   95u,   5}, // Hyperion
    {   96u,   3}, // Masamune
    {   97u,   6}, // Ragnarok
    {   98u,   2}, // Ridill
    {   99u,   4}, // Sargatanas
    {  400u,   6}, // Sagittarius
    {  401u,   6}, // Phantom
    {  402u,   7}, // Alpha
    {  403u,   7}, // Raiden
    {  404u,  11}, // Marilith
    {  405u,  11}, // Seraph
    {  406u,  11}, // Halicarnassus
    {  407u,  11}, // Maduin
    {  408u,  11}, // Cuchulainn
    {  409u,  11}, // Kraken
    {  410u,  11}, // Rafflesia
    {  411u,  11}, // Golem
    { 3000u,  13}, // Cloudtest01
    { 3001u,  13}, // Cloudtest02
}};

struct DataCenterEntry {
    uint8_t id;
    std::string_view name;
};

/// Data center names, from the WorldDCGroupType sheet.
inline constexpr std::array<DataCenterEntry, 19> DATA_CENTER_TABLE{{
    {  1, "Elemental"},
    {  2, "Gaia"},
    {  3, "Mana"},
    {  4, "Aether"},
    {  5, "Primal"},
    {  6, "Chaos"},
    {  7, "Light"},
    {  8, "Crystal"},
    {  9, "Materia"},
    { 10, "Meteor"},
    { 11, "Dynamis"},
    { 12, "Shadow"},
    { 13, "NA Cloud DC (Beta)"},
    { 99, "Beta"},
    {101, "陆行鸟"},
    {102, "莫古力"},
    {103, "猫小胖"},
    {104, "豆豆柴"},
    {201, "Eorzea"},
}};

/// The data center `world` belongs to; 0 for a world the table lacks.
[[nodiscard]] constexpr uint8_t world_data_center(uint16_t world) noexcept {
    const auto it = std::lower_bound(WORLD_TABLE.begin(), WORLD_TABLE.end(), world,
        [](const WorldEntry& entry, uint16_t value) { return entry.id < value; });
    return (it != WORLD_TABLE.end() && it->id == world) ? it->data_center : 0;
}

/// Name of data center `id`, or an empty view when the sheet lacks it.
[[nodiscard]] constexpr std::string_view data_center_name(uint8_t id) noexcept {
    const auto it = std::lower_bound(DATA_CENTER_TABLE.begin(), DATA_CENTER_TABLE.end(), id,
        [](const DataCenterEntry& entry, uint8_t value) { return entry.id < value; });
    return (it != DATA_CENTER_TABLE.end() && it->id == id) ? it->name : std::string_view{};
}

} // namespace hub::game
