#pragma once

// Icon glyphs for the desktop app and the in-game overlay, merged into the
// font atlas at startup (see load_icon_font()). Every macro is a UTF-8
// string literal, so it concatenates straight into a label:
// ICON_SWORDS "  Combat Meter".
//
// Generated by tools/embed_icon_font.py from the Lucide icon font (ISC).
// Do not edit by hand; re-run the script to add a glyph.

namespace hub::common::ui {

/// Codepoint range the subset occupies, for ImFontAtlas::AddFontFromMemoryTTF.
constexpr unsigned short ICON_RANGE_MIN = 0xE038;
constexpr unsigned short ICON_RANGE_MAX = 0xE5DA;

} // namespace hub::common::ui

#define ICON_DASHBOARD  "\xee\x87\x81" // layout-dashboard U+E1C1
#define ICON_SWORDS     "\xee\x8a\xb4" // swords U+E2B4
#define ICON_ACTIVITY   "\xee\x80\xb8" // activity U+E038
#define ICON_SETTINGS   "\xee\x85\x94" // settings U+E154
#define ICON_LAYERS     "\xee\x94\xa9" // layers U+E529
#define ICON_GAMEPAD    "\xee\x83\x9f" // gamepad-2 U+E0DF
#define ICON_PLUG       "\xee\x8d\xbf" // plug U+E37F
#define ICON_CLOCK      "\xee\x82\x87" // clock U+E087
#define ICON_BOLT       "\xee\x86\xb4" // zap U+E1B4
#define ICON_FOLDER     "\xee\x89\x87" // folder-open U+E247
#define ICON_FILE       "\xee\x83\x8c" // file-text U+E0CC
#define ICON_REFRESH    "\xee\x85\x85" // refresh-cw U+E145
#define ICON_PLAY       "\xee\x84\xbc" // play U+E13C
#define ICON_EYE        "\xee\x82\xba" // eye U+E0BA
#define ICON_EYE_OFF    "\xee\x82\xbb" // eye-off U+E0BB
#define ICON_HEART      "\xee\x8d\xae" // heart-pulse U+E36E
#define ICON_HISTORY    "\xee\x87\xb5" // history U+E1F5
#define ICON_SLIDERS    "\xee\x8a\x9a" // sliders-horizontal U+E29A
#define ICON_RESET      "\xee\x85\x88" // rotate-ccw U+E148
#define ICON_SKULL      "\xee\x88\xa1" // skull U+E221
#define ICON_GAUGE      "\xee\x86\xbf" // gauge U+E1BF
#define ICON_SHIELD     "\xee\x87\xbf" // shield-check U+E1FF
#define ICON_TIMER      "\xee\x87\xa0" // timer U+E1E0
#define ICON_TARGET     "\xee\x86\x80" // target U+E180
#define ICON_WARNING    "\xee\x86\x93" // triangle-alert U+E193
#define ICON_SAVE       "\xee\x85\x8d" // save U+E14D
#define ICON_TERMINAL   "\xee\x86\x81" // terminal U+E181
#define ICON_POWER      "\xee\x85\x80" // power U+E140
#define ICON_MONITOR    "\xee\x84\x9d" // monitor U+E11D
#define ICON_BELL       "\xee\x81\x99" // bell U+E059
#define ICON_LOCK       "\xee\x84\x8b" // lock U+E10B
#define ICON_UNLOCK     "\xee\x84\x8c" // lock-open U+E10C
#define ICON_CHEVRON    "\xee\x81\xad" // chevron-down U+E06D
#define ICON_INFO       "\xee\x83\xb9" // info U+E0F9
#define ICON_CHECK      "\xee\x81\xac" // check U+E06C
#define ICON_TRENDING   "\xee\x86\x91" // trending-up U+E191
#define ICON_CHECKLIST  "\xee\x87\x90" // list-checks U+E1D0
#define ICON_CIRCLE_OK  "\xee\x88\xa6" // circle-check U+E226
#define ICON_CIRCLE_X   "\xee\x82\x84" // circle-x U+E084
#define ICON_HOURGLASS  "\xee\x8a\x96" // hourglass U+E296
#define ICON_CROSSHAIR  "\xee\x82\xac" // crosshair U+E0AC
#define ICON_DATABASE   "\xee\x82\xad" // database U+E0AD
#define ICON_WRENCH     "\xee\x86\xb1" // wrench U+E1B1
#define ICON_FLASK      "\xee\x83\x95" // flask-conical U+E0D5
#define ICON_MOVE       "\xee\x84\xa1" // move U+E121
#define ICON_MINIMIZE   "\xee\x84\x9b" // minimize-2 U+E11B
#define ICON_TRASH      "\xee\x86\x8e" // trash-2 U+E18E
#define ICON_DOWNLOAD   "\xee\x82\xb2" // download U+E0B2
#define ICON_SEARCH     "\xee\x85\x91" // search U+E151
#define ICON_SPARKLE    "\xee\x90\x92" // sparkles U+E412
#define ICON_AXE        "\xee\x81\x90" // axe U+E050
#define ICON_SWORD      "\xee\x8a\xb3" // sword U+E2B3
#define ICON_ECLIPSE    "\xee\x96\x9d" // eclipse U+E59D
#define ICON_BOOK       "\xee\x81\x9f" // book-open U+E05F
#define ICON_STAR       "\xee\x85\xb6" // star U+E176
#define ICON_CROSS      "\xee\x87\xa5" // cross U+E1E5
#define ICON_HAND       "\xee\x87\x97" // hand U+E1D7
#define ICON_ARROW_UP   "\xee\x87\xa4" // arrow-big-up U+E1E4
#define ICON_MASK       "\xee\x8a\xaa" // venetian-mask U+E2AA
#define ICON_WORM       "\xee\x97\x9a" // worm U+E5DA
#define ICON_PAW        "\xee\x93\xb5" // paw-print U+E4F5
#define ICON_MUSIC      "\xee\x8d\x8c" // music-4 U+E34C
#define ICON_FEATHER    "\xee\x82\xbe" // feather U+E0BE
#define ICON_FLAME      "\xee\x83\x92" // flame U+E0D2
#define ICON_GEM        "\xee\x89\x82" // gem U+E242
#define ICON_WAND       "\xee\x8d\x97" // wand-sparkles U+E357
#define ICON_DROPLET    "\xee\x82\xb4" // droplet U+E0B4
#define ICON_BRUSH      "\xee\x8b\xa7" // paintbrush U+E2E7
#define ICON_CIRCLE_DOT "\xee\x8d\x85" // circle-dot U+E345
#define ICON_HAMMER     "\xee\x83\xac" // hammer U+E0EC
#define ICON_PICKAXE    "\xee\x97\x86" // pickaxe U+E5C6
