# -*- coding: utf-8 -*-
"""Subsets the Lucide icon font to the glyphs FFXIV Hub's UIs use and emits
src/common/ui/icons.hpp + icons_font.inl. Both the desktop app and the in-game
overlay merge this subset into their font atlas.

Both outputs are checked in, so this only has to be re-run when a glyph is added
to ICONS below. It needs fonttools and the upstream font:

    pip install fonttools
    curl -LO https://unpkg.com/lucide-static@latest/font/Lucide.ttf
    curl -LO https://unpkg.com/lucide-static@latest/font/lucide.css
    python3 tools/embed_icon_font.py --font Lucide.ttf --css lucide.css
"""
import argparse, re, io, os, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--font", default="Lucide.ttf", help="upstream Lucide .ttf")
parser.add_argument("--css", default="lucide.css", help="upstream lucide.css (name -> codepoint map)")
parser.add_argument("--out", default=os.path.join(REPO, "src", "common", "ui"),
                    help="directory to write icons.hpp and icons_font.inl into")
args = parser.parse_args()

CSS  = args.css
TTF  = args.font
SUB  = os.path.join(tempfile.gettempdir(), "lucide-subset.ttf")
DEST = args.out

# C macro suffix -> lucide icon name.
ICONS = [
    ("DASHBOARD",   "layout-dashboard"),
    ("SWORDS",      "swords"),
    ("ACTIVITY",    "activity"),
    ("SETTINGS",    "settings"),
    ("LAYERS",      "layers"),
    ("GAMEPAD",     "gamepad-2"),
    ("PLUG",        "plug"),
    ("CLOCK",       "clock"),
    ("BOLT",        "zap"),
    ("FOLDER",      "folder-open"),
    ("FILE",        "file-text"),
    ("REFRESH",     "refresh-cw"),
    ("PLAY",        "play"),
    ("EYE",         "eye"),
    ("EYE_OFF",     "eye-off"),
    ("HEART",       "heart-pulse"),
    ("HISTORY",     "history"),
    ("SLIDERS",     "sliders-horizontal"),
    ("RESET",       "rotate-ccw"),
    ("SKULL",       "skull"),
    ("GAUGE",       "gauge"),
    ("SHIELD",      "shield-check"),
    ("TIMER",       "timer"),
    ("TARGET",      "target"),
    ("WARNING",     "triangle-alert"),
    ("SAVE",        "save"),
    ("TERMINAL",    "terminal"),
    ("POWER",       "power"),
    ("MONITOR",     "monitor"),
    ("BELL",        "bell"),
    ("LOCK",        "lock"),
    ("UNLOCK",      "lock-open"),
    ("CHEVRON",     "chevron-down"),
    ("INFO",        "info"),
    ("CHECK",       "check"),
    ("TRENDING",    "trending-up"),
    ("CHECKLIST",   "list-checks"),
    ("CIRCLE_OK",   "circle-check"),
    ("CIRCLE_X",    "circle-x"),
    ("HOURGLASS",   "hourglass"),
    ("CROSSHAIR",   "crosshair"),
    ("DATABASE",    "database"),
    ("WRENCH",      "wrench"),
    ("FLASK",       "flask-conical"),
    ("MOVE",        "move"),
    ("MINIMIZE",    "minimize-2"),
    ("TRASH",       "trash-2"),
    ("DOWNLOAD",    "download"),
    ("SEARCH",      "search"),
    ("SPARKLE",     "sparkles"),
]

css = io.open(CSS, encoding="utf-8").read()
table = {}
for name, cp in re.findall(r'\.icon-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', css):
    table[name] = int(cp, 16)

resolved, missing = [], []
for macro, icon in ICONS:
    if icon in table:
        resolved.append((macro, icon, table[icon]))
    else:
        missing.append(icon)
if missing:
    raise SystemExit("icon names not found in lucide.css: %s" % ", ".join(missing))

codepoints = sorted({cp for _, _, cp in resolved})
lo, hi = codepoints[0], codepoints[-1]

pyftsubset = shutil.which("pyftsubset")
if pyftsubset is None:
    raise SystemExit("pyftsubset not on PATH - install fonttools (pip install fonttools)")

subprocess.check_call([
    pyftsubset, TTF,
    "--unicodes=%s" % ",".join("U+%04X" % c for c in codepoints),
    "--output-file=%s" % SUB,
    "--no-hinting", "--desubroutinize", "--drop-tables+=GSUB,GPOS,DSIG",
    "--name-IDs=", "--notdef-outline", "--recalc-bounds",
])

data = io.open(SUB, "rb").read()
os.makedirs(DEST, exist_ok=True)

def utf8_escape(cp):
    return "".join("\\x%02x" % b for b in chr(cp).encode("utf-8"))

# ---- icons.hpp ----
h = io.StringIO()
h.write('#pragma once\n\n')
h.write('// Icon glyphs for the desktop app and the in-game overlay, merged into the\n')
h.write('// font atlas at startup (see load_icon_font()). Every macro is a UTF-8\n')
h.write('// string literal, so it concatenates straight into a label:\n')
h.write('// ICON_SWORDS "  Combat Meter".\n')
h.write('//\n')
h.write('// Generated by tools/embed_icon_font.py from the Lucide icon font (ISC).\n')
h.write('// Do not edit by hand; re-run the script to add a glyph.\n\n')
h.write('namespace hub::common::ui {\n\n')
h.write('/// Codepoint range the subset occupies, for ImFontAtlas::AddFontFromMemoryTTF.\n')
h.write('constexpr unsigned short ICON_RANGE_MIN = 0x%04X;\n' % lo)
h.write('constexpr unsigned short ICON_RANGE_MAX = 0x%04X;\n\n' % hi)
h.write('} // namespace hub::common::ui\n\n')
width = max(len(m) for m, _, _ in resolved)
for macro, icon, cp in resolved:
    h.write('#define ICON_%-*s "%s" // %s U+%04X\n' % (width, macro, utf8_escape(cp), icon, cp))
io.open(os.path.join(DEST, "icons.hpp"), "w", encoding="utf-8").write(h.getvalue())

# ---- icons_font.inl ----
f = io.StringIO()
f.write('// Lucide icon font, subset to the %d glyphs icons.hpp declares (%d bytes).\n' % (len(resolved), len(data)))
f.write('// Generated by tools/embed_icon_font.py; do not edit by hand.\n')
f.write('//\n')
f.write('// Lucide is ISC licensed. Copyright (c) for portions of Lucide are held by\n')
f.write('// Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c)\n')
f.write('// for Lucide are held by Lucide Contributors 2022.\n\n')
f.write('static const unsigned int kIconFontSize = %d;\n' % len(data))
f.write('static const unsigned char kIconFontData[%d] = {\n' % len(data))
for i in range(0, len(data), 16):
    f.write('    ' + ','.join('0x%02x' % b for b in data[i:i+16]) + (',\n' if i + 16 < len(data) else '\n'))
f.write('};\n')
io.open(os.path.join(DEST, "icons_font.inl"), "w", encoding="utf-8").write(f.getvalue())

print("glyphs: %d  range: U+%04X..U+%04X  subset: %d bytes  header array: %d lines"
      % (len(resolved), lo, hi, len(data), (len(data) + 15) // 16))
