#!/usr/bin/env python3
"""Regenerates the game-data tables from a local FFXIV install.

Reads the Excel sheets straight out of the game's SqPack archive - no network,
no third-party data. Re-run after a patch and review the diff on the generated
headers and src/common/game_tables.cpp.

    python3 tools/gen_game_tables.py [--game-dir ~/ffxiv/game]

Small tables are emitted header-only; Action and Status are large enough that
they go in one .cpp instead, so only a single translation unit pays for them.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from xivdata.sqpack import SqPack
from xivdata.excel import Sheet

# Column indices, pinned against known rows (Braver/200, Futures Rewritten/1238).
ACTION_NAME, ACTION_CATEGORY = 0, 3
# Pinned against Heavy Swing/31 (level 1, group 58), Fell Cleave/3549 (level 54) and
# Berserk/38 (group 11). NPC actions carry level 0.
ACTION_CLASSJOB_LEVEL, ACTION_COOLDOWN_GROUP = 12, 41
GCD_COOLDOWN_GROUP = 58
TERRITORY_CFC = 10
CFC_NAME = 43
CLASSJOB_NAME, CLASSJOB_ABBR, CLASSJOB_PARENT, CLASSJOB_ROLE = 0, 1, 29, 47
LIMIT_BREAK_CATEGORY = 9
# Pinned against Battle Litany/786 (1) and Vulnerability Up/638 (2).
STATUS_DESCRIPTION, STATUS_CATEGORY, STATUS_DETRIMENTAL = 1, 6, 2
ACTION_TRANSIENT_DESCRIPTION = 0

# The sentence the game adds to every guaranteed hit since rate buffs started
# raising its damage. Actions put "is increased" first, statuses last.
RATE_BONUS = re.compile(
    r"under an effect that raises (critical hit rate or direct hit rate|critical hit rate|direct hit rate)")
# Only attacks: the actions that grant Life Surge or Reassembled carry the sentence too.
DELIVERS_HIT = re.compile(r"\bdelivers\b", re.IGNORECASE)
# A guaranteed crit that needs a form, e.g. "Opo-opo Form Bonus: Guarantees a critical hit".
FORM_BONUS = re.compile(r"([A-Z][\w-]*) Form Bonus: Guarantees")
# A status that grants every form's bonus at once (Formless Fist).
ALL_FORM_BONUSES = "Additional effects of actions used in these forms will also be triggered"
GUARANTEED_KIND = {
    "critical hit rate": "Crit",
    "direct hit rate": "DirectHit",
    "critical hit rate or direct hit rate": "CritDirectHit",
}

BANNER = """// Generated by tools/gen_game_tables.py from the game's own Excel sheets.
// Do not edit by hand: re-run the generator after a patch instead.
"""


def cpp_string(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write(path, text):
    full = os.path.join(REPO, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"  {path:44} {len(text):>9,} bytes")


def plain(text):
    """Sheet text with its control bytes and line breaks folded to single spaces."""
    return re.sub(r"\s+", " ", re.sub(r"[^\x20-\x7e]", " ", text or ""))


def load(game_dir):
    pack = SqPack(os.path.join(game_dir, "sqpack", "ffxiv"))
    sheets = {}
    actions = [
        (r, row[ACTION_NAME], row[ACTION_CATEGORY], row[ACTION_CLASSJOB_LEVEL], row[ACTION_COOLDOWN_GROUP])
        for r, row in Sheet(pack, "Action").rows()
    ]
    sheets["action"] = sorted((r, n) for r, n, *_ in actions if n)
    sheets["limit_break"] = sorted((r, n) for r, n, c, *_ in actions if c == LIMIT_BREAK_CATEGORY and n)
    player_actions = {r: n for r, n, _, level, _ in actions if n and level > 0}
    sheets["gcd"] = sorted(
        r for r, n, _, level, group in actions if n and level > 0 and group == GCD_COOLDOWN_GROUP)
    statuses = [
        (r, row[0], row[STATUS_CATEGORY], plain(row[STATUS_DESCRIPTION]))
        for r, row in Sheet(pack, "Status").rows()
    ]
    sheets["status"] = sorted((r, n) for r, n, *_ in statuses if n)
    sheets["status_detrimental"] = sorted(r for r, n, c, _ in statuses if n and c == STATUS_DETRIMENTAL)
    if sheets["status_detrimental"][-1] > 0xFFFF:
        raise SystemExit("status ids no longer fit the uint16 table")

    guaranteed, form_bonus, forms = [], [], set()
    for r, row in Sheet(pack, "ActionTransient").rows():
        text = plain(row[ACTION_TRANSIENT_DESCRIPTION])
        match = RATE_BONUS.search(text)
        if r not in player_actions or not match or not DELIVERS_HIT.search(text):
            continue
        form = FORM_BONUS.search(text)
        if form:
            form_bonus.append((r, player_actions[r]))
            forms.add(f"{form.group(1)} Form")
        else:
            guaranteed.append((r, player_actions[r], GUARANTEED_KIND[match.group(1)]))
    sheets["guaranteed_actions"] = sorted(guaranteed)
    sheets["form_bonus_actions"] = sorted(form_bonus)
    sheets["form_bonus_statuses"] = sorted(
        (r, n) for r, n, _, text in statuses if n and (n in forms or ALL_FORM_BONUSES in text))
    sheets["guaranteed_statuses"] = sorted(
        (r, n, GUARANTEED_KIND[m.group(1)])
        for r, n, _, text in statuses if n and (m := RATE_BONUS.search(text)))
    sheets["pet"] = sorted((r, row[0]) for r, row in Sheet(pack, "Pet").rows() if row[0])

    duty = {r: row[CFC_NAME] for r, row in Sheet(pack, "ContentFinderCondition").rows()}
    sheets["territory"] = sorted(
        (r, duty[row[TERRITORY_CFC]])
        for r, row in Sheet(pack, "TerritoryType").rows()
        if duty.get(row[TERRITORY_CFC])
    )
    jobs = {r: row for r, row in Sheet(pack, "ClassJob").rows() if row[CLASSJOB_NAME]}
    sheets["classjob"] = sorted(
        (r, jobs[r][CLASSJOB_NAME].title(), jobs[r][CLASSJOB_ABBR], _role_of(jobs, r))
        for r in jobs
    )
    return sheets


# The game's role column has no Ranged/Caster split, so this reads the job-role column
# (where 2 and 6 are both healer subtypes) and lets a base class inherit from the job
# that grows out of it. Verified to reproduce the repo's hand-written table exactly.
_ROLE_NAMES = {1: "Tank", 2: "Healer", 6: "Healer", 3: "Melee", 4: "Ranged", 5: "Caster"}


def _role_of(jobs, row_id):
    direct = _ROLE_NAMES.get(jobs[row_id][CLASSJOB_ROLE])
    if direct:
        return direct
    for other, row in jobs.items():
        if other != row_id and row[CLASSJOB_PARENT] == row_id:
            inherited = _ROLE_NAMES.get(row[CLASSJOB_ROLE])
            if inherited:
                return inherited
    return "None"


def gen_id_table_header(guard_name, fn, rows, doc):
    entries = "\n".join(
        f"    {{{row_id:>6}u, {cpp_string(name)}}}," for row_id, name in rows
    )
    return f"""{BANNER}#pragma once

#include <algorithm>
#include <array>
#include <cstdint>
#include <string_view>

namespace hub::game {{

struct {guard_name}Entry {{
    uint32_t id;
    std::string_view name;
}};

/// {doc}
inline constexpr std::array<{guard_name}Entry, {len(rows)}> {guard_name.upper()}_TABLE{{{{
{entries}
}}}};

/// Name for `id`, or an empty view when the sheet does not carry it.
[[nodiscard]] constexpr std::string_view {fn}(uint32_t id) noexcept {{
    const auto it = std::lower_bound(
        {guard_name.upper()}_TABLE.begin(), {guard_name.upper()}_TABLE.end(), id,
        [](const {guard_name}Entry& entry, uint32_t value) {{ return entry.id < value; }});
    if (it != {guard_name.upper()}_TABLE.end() && it->id == id) {{
        return it->name;
    }}
    return {{}};
}}

}} // namespace hub::game
"""


def gen_lookup_header(fn, fallback_prefix, doc, extra=""):
    """Header for a table too large to inline: declaration only."""
    return f"""{BANNER}#pragma once

#include <cstdint>
#include <string>
#include <string_view>

namespace hub::game {{

/// {doc}
/// Empty when the sheet carries no such row. Defined in src/common/game_tables.cpp,
/// so including this header does not pull the table into every translation unit.
[[nodiscard]] std::string_view {fn}_sheet_name(uint32_t id) noexcept;

/// Display name, falling back to "{fallback_prefix} <id>" for ids the sheet lacks.
[[nodiscard]] inline std::string {fn}_name(uint32_t id) {{
    const std::string_view name = {fn}_sheet_name(id);
    return name.empty() ? "{fallback_prefix} " + std::to_string(id) : std::string(name);
}}
{extra}
}} // namespace hub::game
"""


def gen_id_set(ids, per_line=12):
    lines = []
    for i in range(0, len(ids), per_line):
        lines.append("    " + " ".join(f"{v}," for v in ids[i:i + per_line]))
    return "\n".join(lines)


def gen_tables_cpp(tables, detrimental, gcd):
    blocks, functions = [], []
    for fn, rows in tables:
        entries = "\n".join(
            f"    {{{row_id:>6}u, {cpp_string(name)}}}," for row_id, name in rows
        )
        upper = fn.upper()
        blocks.append(
            f"constexpr std::array<Entry, {len(rows)}> {upper}{{{{\n{entries}\n}}}};"
        )
        functions.append(
            f"std::string_view {fn}_sheet_name(uint32_t id) noexcept {{\n"
            f"    return lookup({upper}, id);\n}}"
        )
    blocks.append(
        f"// Status sheet category 2: the game's own debuff flag.\n"
        f"constexpr std::array<uint16_t, {len(detrimental)}> DETRIMENTAL_STATUS{{{{\n"
        f"{gen_id_set(detrimental)}\n}}}};"
    )
    functions.append(
        "bool status_is_detrimental(uint32_t id) noexcept {\n"
        "    return id <= 0xFFFF && std::binary_search(\n"
        "        DETRIMENTAL_STATUS.begin(), DETRIMENTAL_STATUS.end(), static_cast<uint16_t>(id));\n}"
    )
    blocks.append(
        f"// Player actions on the global cooldown (Action sheet cooldown group {GCD_COOLDOWN_GROUP}).\n"
        f"constexpr std::array<uint32_t, {len(gcd)}> GCD_ACTION{{{{\n"
        f"{gen_id_set(gcd)}\n}}}};"
    )
    functions.append(
        "bool is_gcd_action(uint32_t id) noexcept {\n"
        "    return std::binary_search(GCD_ACTION.begin(), GCD_ACTION.end(), id);\n}"
    )
    body = "\n\n".join(blocks)
    fns = "\n\n".join(functions)
    return f"""{BANNER}
#include "hub/game/actions.hpp"
#include "hub/game/status.hpp"

#include <algorithm>
#include <array>
#include <span>

namespace hub::game {{
namespace {{

struct Entry {{
    uint32_t id;
    std::string_view name;
}};

{body}

std::string_view lookup(std::span<const Entry> table, uint32_t id) noexcept {{
    const auto it = std::lower_bound(
        table.begin(), table.end(), id,
        [](const Entry& entry, uint32_t value) {{ return entry.id < value; }});
    return (it != table.end() && it->id == id) ? it->name : std::string_view{{}};
}}

}} // namespace

{fns}

}} // namespace hub::game
"""


def gen_limit_break_header(rows):
    entries = "\n".join(
        f"    {row_id:>6},{' ' * max(1, 8 - len(str(row_id)))}// {name}" for row_id, name in rows
    )
    return f"""{BANNER}#pragma once

#include <algorithm>
#include <array>
#include <cstdint>

namespace hub::game {{

/// Synthetic combatant id holding Limit Break damage. The game reports the casting
/// player as the source, so the meter needs an id of its own to move that damage off
/// the player's row; picked above every real entity id so it cannot collide with one.
/// Not 0xE0000000 - that is the game's "no owner / not networked" sentinel.
constexpr uint32_t LIMIT_BREAK_COMBATANT_ID = 0xFFFFFFFA;

/// Every named action the game files under ActionCategory 9 ("Limit Break"), sorted.
/// The category also holds duty-action and NPC limit breaks, so callers must check
/// that the source is friendly before treating a hit as party limit break damage.
constexpr std::array<uint32_t, {len(rows)}> LIMIT_BREAK_ACTIONS{{{{
{entries}
}}}};

/// True for an action in the game's Limit Break category.
[[nodiscard]] constexpr bool is_limit_break_action(uint32_t action_id) noexcept {{
    return std::binary_search(LIMIT_BREAK_ACTIONS.begin(), LIMIT_BREAK_ACTIONS.end(), action_id);
}}

}} // namespace hub::game
"""


def gen_guaranteed_hits_header(actions, statuses, form_actions, form_statuses):
    def entries(rows):
        return "\n".join(
            f"    {{{row_id:>6}u, {'GuaranteedHit::' + kind + '},':<30} // {name}"
            for row_id, name, kind in rows)

    def ids(rows):
        return "\n".join(f"    {row_id:>6}u, // {name}" for row_id, name in rows)

    return f"""{BANNER}#pragma once

#include <algorithm>
#include <array>
#include <cstdint>

namespace hub::game {{

/// What a hit is guaranteed to be. Rate buffs raise a guaranteed hit's damage
/// instead of its chance.
enum class GuaranteedHit : uint8_t {{
    None = 0,
    Crit = 1,
    DirectHit = 2,
    CritDirectHit = 3,
}};

struct GuaranteedHitEntry {{
    uint32_t id;
    GuaranteedHit hit;
}};

/// Actions whose text says rate buffs raise their damage: every one is a guaranteed
/// hit, from the ActionTransient sheet.
constexpr std::array<GuaranteedHitEntry, {len(actions)}> GUARANTEED_HIT_ACTIONS{{{{
{entries(actions)}
}}}};

/// Statuses that make the holder's next weaponskills guaranteed hits, from the same
/// sentence on the Status sheet.
constexpr std::array<GuaranteedHitEntry, {len(statuses)}> GUARANTEED_HIT_STATUSES{{{{
{entries(statuses)}
}}}};

/// Actions that only crit for certain with their form bonus.
constexpr std::array<uint32_t, {len(form_actions)}> FORM_BONUS_CRIT_ACTIONS{{{{
{ids(form_actions)}
}}}};

/// Statuses that grant that form bonus.
constexpr std::array<uint32_t, {len(form_statuses)}> FORM_BONUS_STATUSES{{{{
{ids(form_statuses)}
}}}};

namespace detail {{
[[nodiscard]] constexpr GuaranteedHit find_guaranteed(const auto& table, uint32_t id) noexcept {{
    const auto it = std::lower_bound(table.begin(), table.end(), id,
        [](const GuaranteedHitEntry& entry, uint32_t value) {{ return entry.id < value; }});
    return (it != table.end() && it->id == id) ? it->hit : GuaranteedHit::None;
}}
}} // namespace detail

/// What `action_id` always lands as; None when it rolls like any other hit.
[[nodiscard]] constexpr GuaranteedHit guaranteed_hit_of_action(uint32_t action_id) noexcept {{
    return detail::find_guaranteed(GUARANTEED_HIT_ACTIONS, action_id);
}}

/// What a weaponskill used under `status_id` lands as; None for any other status.
[[nodiscard]] constexpr GuaranteedHit guaranteed_hit_of_status(uint32_t status_id) noexcept {{
    return detail::find_guaranteed(GUARANTEED_HIT_STATUSES, status_id);
}}

[[nodiscard]] constexpr bool is_form_bonus_crit_action(uint32_t action_id) noexcept {{
    return std::binary_search(FORM_BONUS_CRIT_ACTIONS.begin(), FORM_BONUS_CRIT_ACTIONS.end(), action_id);
}}

[[nodiscard]] constexpr bool is_form_bonus_status(uint32_t status_id) noexcept {{
    return std::binary_search(FORM_BONUS_STATUSES.begin(), FORM_BONUS_STATUSES.end(), status_id);
}}

}} // namespace hub::game
"""


def gen_job_header(jobs):
    def switch(body):
        return "\n".join(body)

    enum = "\n".join(f"    {abbr} = {rid}," for rid, _, abbr, _ in jobs)
    names = switch(f'        case Job::{abbr}: return "{name}";' for rid, name, abbr, _ in jobs)
    abbrs = switch(f'        case Job::{abbr}: return "{abbr}";' for rid, _, abbr, _ in jobs)

    by_role = {}
    for _, _, abbr, role in jobs:
        by_role.setdefault(role, []).append(abbr)
    role_arms = []
    for role in ("Tank", "Healer", "Melee", "Ranged", "Caster"):
        if role not in by_role:
            continue
        cases = "\n".join(f"        case Job::{a}:" for a in by_role[role])
        role_arms.append(f"{cases}\n            return Role::{role};")
    roles = "\n\n".join(role_arms)

    return f"""{BANNER}#pragma once

#include <cstdint>
#include <string_view>

namespace hub::game {{

enum class Job : uint32_t {{
    None = 0,
{enum}
}};

/// Roles as this project groups them. The game's own role column does not split
/// physical ranged from casters, so job_to_role below derives that distinction.
enum class Role : uint8_t {{
    None = 0,
    Tank = 1,
    Healer = 2,
    Melee = 3,
    Ranged = 4,
    Caster = 5
}};

[[nodiscard]] constexpr std::string_view to_string(Job job) noexcept {{
    switch (job) {{
{names}
        default: return "Unknown";
    }}
}}

[[nodiscard]] constexpr std::string_view job_abbreviation(Job job) noexcept {{
    switch (job) {{
{abbrs}
        default: return "???";
    }}
}}

[[nodiscard]] constexpr Role job_to_role(Job job) noexcept {{
    switch (job) {{
{roles}

        default:
            return Role::None;
    }}
}}

[[nodiscard]] constexpr std::string_view to_string(Role role) noexcept {{
    switch (role) {{
        case Role::Tank: return "Tank";
        case Role::Healer: return "Healer";
        case Role::Melee: return "Melee";
        case Role::Ranged: return "Ranged";
        case Role::Caster: return "Caster";
        default: return "None";
    }}
}}

}} // namespace hub::game
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--game-dir",
        default=os.environ.get("FFXIV_HUB_GAME_DIR", os.path.expanduser("~/ffxiv/game")),
        help="FFXIV game directory holding sqpack/ (default: $FFXIV_HUB_GAME_DIR or ~/ffxiv/game)",
    )
    args = parser.parse_args()

    print(f"reading {args.game_dir}")
    sheets = load(args.game_dir)
    for name, rows in sheets.items():
        print(f"  {name:12} {len(rows):>6} rows")
    print()

    write("include/hub/game/territory.hpp", gen_id_table_header(
        "Territory", "territory_name", sheets["territory"],
        "Duty name per territory id, from TerritoryType -> ContentFinderCondition."))

    write("include/hub/game/actions.hpp", gen_lookup_header(
        "action", "Action", "Name from the game's Action sheet.", extra=f"""
/// True for a player action on the global cooldown (cooldown group {GCD_COOLDOWN_GROUP}).
/// Defined in src/common/game_tables.cpp.
[[nodiscard]] bool is_gcd_action(uint32_t id) noexcept;
"""))
    write("include/hub/game/status.hpp", gen_lookup_header(
        "status", "Status", "Name from the game's Status sheet.", extra="""
/// True for a status the game files as a debuff (Status sheet category 2), whoever
/// applied it. Defined in src/common/game_tables.cpp.
[[nodiscard]] bool status_is_detrimental(uint32_t id) noexcept;
"""))
    write("src/common/game_tables.cpp", gen_tables_cpp(
        [("action", sheets["action"]), ("status", sheets["status"])],
        sheets["status_detrimental"], sheets["gcd"]))
    write("include/hub/game/limit_break.hpp", gen_limit_break_header(sheets["limit_break"]))
    write("include/hub/game/guaranteed_hits.hpp", gen_guaranteed_hits_header(
        sheets["guaranteed_actions"], sheets["guaranteed_statuses"],
        sheets["form_bonus_actions"], sheets["form_bonus_statuses"]))
    write("include/hub/game/job.hpp", gen_job_header(sheets["classjob"]))


if __name__ == "__main__":
    main()
